import Head from "next/head";
import {
  createTask,
  fetchStats,
  fetchTasks,
  removeTask,
  updateTask,
} from "../src/services/todo.services";
import { useQuery } from "react-query";
import TaskCard from "../src/components/task-card";
import TaskInput from "../src/components/task-input";

export async function getServerSideProps() {
  const tasks = await fetchTasks();
  const stats = await fetchStats();
  return { props: { tasks, stats } };
}

export default function Home(props) {
  const { isSuccess, isLoading, isError, data } = useQuery(
    "tasks",
    fetchTasks,
    { initialData: props.tasks }
  );

  const stats = useQuery("stats", fetchStats, { initialStats: props.stats });

  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="p-10">
        {isError && <p>There has been an error</p>}
        {isLoading && <p>Loading tasks</p>}
        {isSuccess &&
          data.map((task) => (
            <TaskCard
              task={task}
              removeTask={removeTask}
              updateTask={updateTask}
            />
          ))}
        <TaskInput />
      </main>
    </div>
  );
}
